name: midyear
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.0.0
  flutter_svg: ^2.0.9
  # google_maps_flutter: ^2.5.0
  sqflite: ^2.3.0
  path: ^1.8.3
  gsheets: ^0.5.0
  google_fonts: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  fonts: 
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf

  assets:
  - assets/images/
  - assets/svg/





